# -*- coding: utf-8 -*-
{
    'name': "Sale Custom Ivess",
    'version': '19.0.0.0.0',
    'description': """
    """,
    'author': "Eynes",
    'category': 'Sale',
    'depends': [
        'base',
        'account',
        'sale',
        'fleet',
        'mail',
        'l10n_ar_eynes',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/ir_data.xml',
        'data/ir_sequence.xml',
        'data/res_groups.xml',
        'views/client_type.xml',
        'views/delivery_route.xml',
        'views/delivery_route_number.xml',
        'views/account_move.xml',
        'views/no_purchase_reason.xml',
        'views/product_template.xml',
        'views/replacement_reason.xml',
        'views/res_partner_water_consumption.xml',
        'views/res_partner.xml',
        'views/role.xml',
        'views/res_company.xml',
        'views/sale_order.xml',
        'views/template_delivery_route.xml',
        'views/visit_status.xml',
        'views/water_container.xml',
        'views/purchase_order.xml',
        'views/menuitems.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
