# Copyright 2026 Eynes
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).
"""Layout posicional de los registros 010 (cabecera), 020 (orden de pago),
025 (instrumento adicional, multi-Echeq), 090 (proveedor beneficiario) y 095
(pie) del archivo BBVA "Pago a Proveedores".

Posiciones/longitudes validadas carácter por carácter contra
``docs/JUMI_OP_ECHEQS_2026-06-23.txt`` (registros simples) y
``docs/IMPA_OP_ECHEQS_2026-06-23 copy.txt`` (una orden con 4 Echeqs, incluye
registro 025) y contra ``docs/matriz_campos_bbva.csv`` /
``docs/Analisis_registro_025_BBVA_IMPA.xlsx`` / el Apéndice A de
``docs/ANALISIS_Y_DISENO.md``.
"""

REGISTRO_010 = {
    'ident_registro': {
        'start_pos': 1,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_reg': {
        'start_pos': 5,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_doc_empresa': {
        'start_pos': 8,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'cuit_empresa': {
        'start_pos': 12,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'secuencia': {
        'start_pos': 25,
        'length': 6,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'moneda': {
        'start_pos': 31,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'importe_total': {
        'start_pos': 32,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'forma_pago': {
        'start_pos': 45,
        'length': 2,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'forma_cobro': {
        'start_pos': 47,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'dispon_pago': {
        'start_pos': 48,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'deposito': {
        'start_pos': 49,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'fecha_emision': {
        'start_pos': 50,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'fecha_entrega': {
        'start_pos': 58,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'fecha_pago': {
        'start_pos': 66,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'entidad': {
        'start_pos': 74,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'suc_cta_debito': {
        'start_pos': 78,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'dv_cta_debito': {
        'start_pos': 82,
        'length': 2,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_cta_debito': {
        'start_pos': 84,
        'length': 2,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'moneda_cta_debito': {
        'start_pos': 86,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'nro_cta_debito': {
        'start_pos': 87,
        'length': 7,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'cantidad_ordenes': {
        'start_pos': 94,
        'length': 7,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'entrega_lote': {
        'start_pos': 101,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'suc_entrega_lote': {
        'start_pos': 102,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'filler_1': {
        'start_pos': 106,
        'length': 6,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'libre_impresion': {
        'start_pos': 112,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'nombre_fichero': {
        'start_pos': 113,
        'length': 12,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'fecha_proceso': {
        'start_pos': 125,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'contrato_prov': {
        'start_pos': 133,
        'length': 20,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'filler_final': {
        'start_pos': 153,
        'length': 698,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
}

REGISTRO_020 = {
    'ident_registro': {
        'start_pos': 1,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_reg': {
        'start_pos': 5,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_doc_empresa': {
        'start_pos': 8,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'cuit_empresa': {
        'start_pos': 12,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'secuencia': {
        'start_pos': 25,
        'length': 6,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'pro_nro_beneficiario': {
        'start_pos': 31,
        'length': 15,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'nro_minuta': {
        'start_pos': 46,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'importe': {
        'start_pos': 54,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'nro_cert_ret_ganancias': {
        'start_pos': 67,
        'length': 14,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'regimen_ganancias': {
        'start_pos': 81,
        'length': 30,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'imp_ret_ganancias': {
        'start_pos': 111,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'nro_cert_ret_iva': {
        'start_pos': 124,
        'length': 14,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'regimen_iva': {
        'start_pos': 138,
        'length': 30,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_nro_ord': {
        'start_pos': 168,
        'length': 15,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'filler_1': {
        'start_pos': 183,
        'length': 8,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'acred_a_susp': {
        'start_pos': 191,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'ipermfin': {
        'start_pos': 192,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'cli_aje': {
        'start_pos': 193,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'ncuit_pago': {
        'start_pos': 194,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'nome_pago': {
        'start_pos': 207,
        'length': 40,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'tipo_documento': {
        'start_pos': 247,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'nro_documento': {
        'start_pos': 250,
        'length': 11,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'suc_entrega': {
        'start_pos': 261,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'fecha_entrega': {
        'start_pos': 265,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'fecha_pago': {
        'start_pos': 273,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'forma_pago': {
        'start_pos': 281,
        'length': 2,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'forma_cobro': {
        'start_pos': 283,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'dispon_p': {
        'start_pos': 284,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'deposito': {
        'start_pos': 285,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'nro_cheque': {
        'start_pos': 286,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'cod_devolucion': {
        'start_pos': 299,
        'length': 6,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'desc_devolucion': {
        'start_pos': 305,
        'length': 40,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'filler_final': {
        'start_pos': 345,
        'length': 506,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
}

REGISTRO_025 = {
    'ident_registro': {
        'start_pos': 1,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_reg': {
        'start_pos': 5,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_doc_empresa': {
        'start_pos': 8,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'cuit_empresa': {
        'start_pos': 12,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'secuencia': {
        'start_pos': 25,
        'length': 6,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'filler_1': {
        'start_pos': 31,
        'length': 15,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'nro_minuta': {
        'start_pos': 46,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'importe': {
        'start_pos': 54,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'filler_2': {
        'start_pos': 67,
        'length': 125,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'ipermfin': {
        'start_pos': 192,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'filler_3': {
        'start_pos': 193,
        'length': 58,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_cbu_nro': {
        'start_pos': 251,
        'length': 22,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'fecha_pago': {
        'start_pos': 273,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'forma_pago': {
        'start_pos': 281,
        'length': 2,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'filler_4': {
        'start_pos': 283,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'dispon_p': {
        'start_pos': 284,
        'length': 1,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'filler_5': {
        'start_pos': 285,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'nro_cheque': {
        'start_pos': 286,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'cod_devolucion': {
        'start_pos': 299,
        'length': 6,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'desc_devolucion': {
        'start_pos': 305,
        'length': 40,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'filler_final': {
        'start_pos': 345,
        'length': 506,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
}

REGISTRO_090 = {
    'ident_registro': {
        'start_pos': 1,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_reg': {
        'start_pos': 5,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_doc_empresa': {
        'start_pos': 8,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'cuit_empresa': {
        'start_pos': 12,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'secuencia': {
        'start_pos': 25,
        'length': 6,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'pro_nro_ord': {
        'start_pos': 31,
        'length': 15,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_nro_benef': {
        'start_pos': 46,
        'length': 15,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'pro_est_benef': {
        'start_pos': 61,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_docto_tip': {
        'start_pos': 62,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_docto_nro': {
        'start_pos': 65,
        'length': 11,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'pro_denomina': {
        'start_pos': 76,
        'length': 40,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_catego': {
        'start_pos': 116,
        'length': 2,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_permit_finan': {
        'start_pos': 118,
        'length': 1,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_cus_tip': {
        'start_pos': 119,
        'length': 2,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_cus_suc': {
        'start_pos': 121,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_cus_nro': {
        'start_pos': 124,
        'length': 10,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_cbu_nro': {
        'start_pos': 134,
        'length': 22,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_ingbrts': {
        'start_pos': 156,
        'length': 11,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_calle': {
        'start_pos': 167,
        'length': 24,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_numero': {
        'start_pos': 191,
        'length': 5,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_depto': {
        'start_pos': 196,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_piso': {
        'start_pos': 199,
        'length': 2,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_localid': {
        'start_pos': 201,
        'length': 28,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_cpostal': {
        'start_pos': 229,
        'length': 5,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_codprov': {
        'start_pos': 234,
        'length': 2,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'pro_codpais': {
        'start_pos': 236,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_email': {
        'start_pos': 239,
        'length': 40,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'pro_entrega_block': {
        'start_pos': 279,
        'length': 72,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_telef_block': {
        'start_pos': 351,
        'length': 33,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_telef_alter_block': {
        'start_pos': 384,
        'length': 33,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_nom1': {
        'start_pos': 417,
        'length': 25,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_tip1': {
        'start_pos': 442,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_doc1': {
        'start_pos': 445,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_autoriza_nom2': {
        'start_pos': 453,
        'length': 25,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_tip2': {
        'start_pos': 478,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_doc2': {
        'start_pos': 481,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_autoriza_nom3': {
        'start_pos': 489,
        'length': 25,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_tip3': {
        'start_pos': 514,
        'length': 3,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_autoriza_doc3': {
        'start_pos': 517,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': False,
    },
    'pro_datos': {
        'start_pos': 525,
        'length': 100,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
    'pro_minuta': {
        'start_pos': 625,
        'length': 8,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'filler_final': {
        'start_pos': 633,
        'length': 218,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
}

REGISTRO_095 = {
    'ident_registro': {
        'start_pos': 1,
        'length': 4,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_reg': {
        'start_pos': 5,
        'length': 3,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tipo_doc_empresa': {
        'start_pos': 8,
        'length': 4,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': True,
    },
    'cuit_empresa': {
        'start_pos': 12,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'secuencia': {
        'start_pos': 25,
        'length': 6,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'suma_importe': {
        'start_pos': 31,
        'length': 13,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'cant_pagos': {
        'start_pos': 44,
        'length': 7,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'tot_reg': {
        'start_pos': 51,
        'length': 10,
        'type': 'string',
        'alignment': 'right',
        'padding': '0',
        'required': True,
    },
    'filler_final': {
        'start_pos': 61,
        'length': 790,
        'type': 'string',
        'alignment': 'left',
        'padding': ' ',
        'required': False,
    },
}
